Gemini Call

In [27]:
import requests
import json
# Gen AI packages Gemini
from google import genai
from google.genai import types

In [29]:
# The client gets the API key from the environment variable `GEMINI_API_KEY`.
token = ''
client = genai.Client(api_key=token)

def chart_analysis(prompt, image):
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[prompt],
        config=types.GenerateContentConfig(
            system_instruction='You are a helpful assistant',
            temperature=0.1
        )
    )
    return response.text

AI learns from data to recognize patterns and make decisions or predictions.

Forex Factory

In [34]:
import pandas as pd
import requests

In [41]:
response = requests.get('https://nfs.faireconomy.media/ff_calendar_thisweek.json')
df_forex_factory = pd.DataFrame(response.json())
display(df_forex_factory)

,title,country,date,impact,forecast,previous
0,BusinessNZ Services Index,NZD,2025-08-17T18:30:00-04:00,Low,,47.3
1,Rightmove HPI m/m,GBP,2025-08-17T19:01:00-04:00,Low,,-1.2%
2,Tertiary Industry Activity m/m,JPY,2025-08-18T00:30:00-04:00,Low,0.1%,0.6%
3,Trade Balance,EUR,2025-08-18T05:00:00-04:00,Low,18.1B,16.2B
4,Housing Starts,CAD,2025-08-18T08:15:00-04:00,Low,270K,284K
...,...,...,...,...,...,...
81,Fed Chair Powell Speaks,USD,2025-08-22T10:00:00-04:00,High,,
82,Jackson Hole Symposium,All,2025-08-22T12:15:00-04:00,High,,
83,Jackson Hole Symposium,All,2025-08-23T12:15:00-04:00,Medium,,
84,ECB President Lagarde Speaks,EUR,2025-08-23T12:25:00-04:00,Medium,,
85,BOE Gov Bailey Speaks,GBP,2025-08-23T12:25:00-04:00,High,,

News API ON HOLD

In [51]:
import requests
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [57]:
token = ''
url = 'https://newsapi.org/v2/everything'
payload = {
    'q': 'USDCAD',
    'sources'
    'from': '2025-08-05',
    'sortBy': 'popularity',
    'language': 'en',
    'pageSize': 100,
    'apiKey': token
}
response = requests.get(url, params=payload)
df_news = pd.DataFrame(response.json()['articles'])
display(df_news)

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'GlobeNewswire'}",Osisko Development Corp,Osisko Development Reports Second Quarter 2025 Results,"(All dollar amounts are expressed in Canadian dollars, unless stated otherwise) MONTREAL, Aug. 12, 2025 (GLOBE NEWSWIRE) -- Osisko Development Corp.......",https://www.globenewswire.com/news-release/2025/08/13/3132257/0/en/Osisko-Development-Reports-Second-Quarter-2025-Results.html,https://ml.globenewswire.com/Resource/Download/01a211d6-c079-4a49-a972-11a0e55704bd,2025-08-13T00:30:00Z,"(All dollar amounts are expressed in Canadian dollars, unless stated otherwise)\r\nMONTREAL, Aug. 12, 2025 (GLOBE NEWSWIRE) -- Osisko Development Corp. (NYSE: ODV, TSXV: ODV) (""Osisko Development"" or t… [+35016 chars]"

Oanda

In [71]:
import v20
from datetime import datetime
import time
from dateutil.relativedelta import relativedelta

In [59]:
# Practice Acct No:
# Practice API Token:
acct = ''
token = ''

# REST API - historical price action, place orders, account info, etc
rest_url = 'api-fxpractice.oanda.com'

In [72]:
# Function definition to convert json to pandas dataframe
def json_to_pandas(json):
    json_file = json.json()
    price_json = json_file['candles']
    times = []
    close_price, high_price, low_price, open_price = [], [], [], []

    for candle in price_json:
        times.append(candle['time'])
        close_price.append(float(candle['mid']['c']))
        high_price.append(float(candle['mid']['h']))
        low_price.append(float(candle['mid']['l']))
        open_price.append(float(candle['mid']['o']))

    df = pd.DataFrame({'datetime': pd.to_datetime(times).tz_localize(None),
                       'close': close_price,
                       'high': high_price,
                       'low': low_price,
                       'open': open_price})
    df.index = pd.to_datetime(times).tz_localize(None)
    return df

In [73]:
# for currency in li_currency:
currency = 'GBP_USD'
interval = {'M15'}
print(f'---------- {currency} ----------')
# Get current prices
rest = v20.Context(hostname=rest_url, token=token, port=443)

response_rest = rest.pricing.get(accountID=acct, instruments=currency)
json.loads(response_rest.body["prices"][0].json())
bid_at_trade = json.loads(response_rest.body["prices"][0].json())['bids'][0]['price']
ask_at_trade = json.loads(response_rest.body["prices"][0].json())['asks'][0]['price']
spread_at_trade = round(abs(bid_at_trade - ask_at_trade),5)
print(f'Bid at Trade: {bid_at_trade}')
print(f'Ask at Trade: {ask_at_trade}')
print(f'Spread at Trade: {spread_at_trade}')

# Get historical prices
start_time = datetime.now() - relativedelta(days=30)
start_time = time.mktime(start_time.timetuple())
end_time = time.mktime(datetime.now().timetuple())

header = {'Authorization': 'Bearer ' + token}
query = {'from': str(start_time), 'to': str(end_time), 'granularity': interval}
candles_path = f'/v3/accounts/{acct}/instruments/{currency}/candles'
response = requests.get('https://' + rest_url + candles_path,
                        headers=header,
                        params=query)
print(f'Response to historical query: {response}')

df = json_to_pandas(response)

---------- GBP_USD ----------
Bid at Trade: 1.35558
Ask at Trade: 1.35578
Spread at Trade: 0.0002
Response to historical query: <Response [200]>

In [74]:
display(df)

                               datetime    close     high      low     open
2025-07-20 21:00:00 2025-07-20 21:00:00  1.34088  1.34179  1.34088  1.34179
2025-07-20 21:30:00 2025-07-20 21:30:00  1.34288  1.34319  1.34198  1.34263
2025-07-20 21:45:00 2025-07-20 21:45:00  1.34185  1.34310  1.34180  1.34281
2025-07-20 22:00:00 2025-07-20 22:00:00  1.34200  1.34235  1.34118  1.34235
2025-07-20 22:15:00 2025-07-20 22:15:00  1.34170  1.34202  1.34156  1.34200
...                                 ...      ...      ...      ...      ...
2025-08-17 23:00:00 2025-08-17 23:00:00  1.35575  1.35624  1.35572  1.35620
2025-08-17 23:15:00 2025-08-17 23:15:00  1.35560  1.35581  1.35541  1.35575
2025-08-17 23:30:00 2025-08-17 23:30:00  1.35570  1.35575  1.35551  1.35560
2025-08-17 23:45:00 2025-08-17 23:45:00  1.35561  1.35581  1.35544  1.35569
2025-08-18 00:00:00 2025-08-18 00:00:00  1.35568  1.35568  1.35558  1.35560

[1932 rows x 5 columns]

In [61]:
rest = v20.Context(hostname=rest_url, token=token, port=443)
currency = 'GBP_USD'

response_rest = rest.pricing.get(accountID=acct, instruments=currency)
json.loads(response_rest.body["prices"][0].json())
bid_at_trade = json.loads(response_rest.body["prices"][0].json())['bids'][0]['price']
ask_at_trade = json.loads(response_rest.body["prices"][0].json())['asks'][0]['price']
spread_at_trade = round(abs(bid_at_trade - ask_at_trade),5)
print(f'Bid at Trade: {bid_at_trade}')
print(f'Ask at Trade: {ask_at_trade}')
print(f'Spread at Trade: {spread_at_trade}')

Bid at Trade: 1.3555
Ask at Trade: 1.35571
Spread at Trade: 0.00021

In [69]:
print(response_rest.body['prices'][0].json())

{"type":"PRICE","instrument":"GBP_USD","time":"2025-08-17T23:39:28.023363935Z","status":"tradeable","tradeable":true,"bids":[{"price":1.3555,"liquidity":500000},{"price":1.35549,"liquidity":500000},{"price":1.35548,"liquidity":2000000},{"price":1.35547,"liquidity":2000000},{"price":1.35545,"liquidity":5000000},{"price":1.35541,"liquidity":10000000},{"price":1.35532,"liquidity":5000000}],"asks":[{"price":1.35571,"liquidity":500000},{"price":1.35573,"liquidity":2500000},{"price":1.35575,"liquidity":2000000},{"price":1.35576,"liquidity":5000000},{"price":1.35581,"liquidity":10000000},{"price":1.3559,"liquidity":5000000}],"closeoutBid":1.35532,"closeoutAsk":1.3559,"quoteHomeConversionFactors":{"positiveUnits":"1.0","negativeUnits":"1.0"}}